# Generated by Django 6.0.7 on 2026-07-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="preferred_language",
            field=models.CharField(
                choices=[("Bulgarian", "BG"), ("English", "EN")], default="Bulgarian"
            ),
        ),
    ]
