# Generated by Django 6.0.7 on 2026-07-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_customuser_is_staff_customuser_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
