# Generated by Django 6.0.7 on 2026-07-23 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courts", "0005_alter_court_name_alter_court_sport_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExceptionalUnavailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unavailability",
                        to="clubs.club",
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptional_unavailability",
                        to="courts.court",
                    ),
                ),
            ],
        ),
    ]
