# Generated by Django 6.0.7 on 2026-07-23 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OpeningHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.CharField(
                        choices=[
                            ("Monday", "Mon"),
                            ("Tuesday", "Tue"),
                            ("Wednesday", "Wed"),
                            ("Thursday", "Thu"),
                            ("Friday", "Fry"),
                            ("Saturday", "Sat"),
                            ("Sunday", "Sun"),
                        ]
                    ),
                ),
                ("opening_hour", models.TimeField()),
                ("closing_hour", models.TimeField()),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_hour",
                        to="clubs.club",
                    ),
                ),
            ],
        ),
    ]
