# Generated by Django 6.0.7 on 2026-07-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_court_court_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='court',
            old_name='is_covered',
            new_name='is_indoor',
        ),
        migrations.RenameField(
            model_name='court',
            old_name='court_type',
            new_name='surface_type',
        ),
        migrations.AddField(
            model_name='court',
            name='name',
            field=models.CharField(default='Tennis 1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='court',
            name='sport_type',
            field=models.CharField(choices=[('Tennis', 'Tennis')], default='Tennis'),
            preserve_default=False,
        ),
    ]
