# Generated by Django 6.0.7 on 2026-07-23 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("clubs", "0001_initial"),
        ("clubs", "0002_club_address_club_description_club_email_club_phone_and_more"),
        ("clubs", "0003_openinghours"),
        ("clubs", "0004_openinghours_closing_hour_openinghours_opening_hour"),
        ("clubs", "0005_club_employees"),
        ("clubs", "0006_alter_club_name"),
        ("clubs", "0007_alter_club_city"),
        ("clubs", "0008_alter_openinghours_closing_hour_and_more"),
        ("clubs", "0009_rename_club_id_openinghours_club_and_more"),
        ("clubs", "0010_alter_openinghours_closing_hour_and_more"),
        ("clubs", "0011_alter_openinghours_closing_hour_and_more"),
        ("clubs", "0012_remove_exceptionalunavailability_day_end_and_more"),
        ("clubs", "0013_alter_openinghours_closing_hour_and_more"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("city", models.CharField(choices=[("Sofia", "SOF")], default="Sofia")),
                ("address", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("email", models.EmailField(default="email@mail.com", max_length=254)),
                ("phone", models.CharField(default="0123456789", max_length=12)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "employees",
                    models.ManyToManyField(
                        related_name="club", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
