# Generated by Django 6.0.7 on 2026-07-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='email',
            field=models.EmailField(default='email@mail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='phone',
            field=models.CharField(default='0123456789', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='city',
            field=models.CharField(choices=[('Sofia', 'SOF')]),
        ),
    ]
