# Generated by Django 6.0.7 on 2026-07-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_address_club_description_club_email_club_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thu'), ('Friday', 'Fry'), ('Saturday', 'Sat'), ('Sunday', 'Sun')])),
                ('club_id', models.ManyToManyField(to='clubs.club')),
            ],
        ),
    ]
