# Generated by Django 6.0.7 on 2026-07-12 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0004_openinghours_closing_hour_openinghours_opening_hour"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="employees",
            field=models.ManyToManyField(
                related_name="club", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
