# Generated by Django 6.0.7 on 2026-07-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0005_club_employees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
