# Generated by Django 6.0.7 on 2026-07-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0006_alter_club_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="city",
            field=models.CharField(choices=[("Sofia", "SOF")], default="Sofia"),
        ),
    ]
