# Generated by Django 6.0.7 on 2026-07-14 11:44

import common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0007_alter_club_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openinghours",
            name="closing_hour",
            field=models.IntegerField(
                validators=[common.validators.ValidHoursValidator()]
            ),
        ),
        migrations.RemoveField(
            model_name="openinghours",
            name="club_id",
        ),
        migrations.AlterField(
            model_name="openinghours",
            name="opening_hour",
            field=models.IntegerField(
                validators=[common.validators.ValidHoursValidator()]
            ),
        ),
        migrations.AddField(
            model_name="openinghours",
            name="club_id",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="clubs.club"
            ),
            preserve_default=False,
        ),
    ]
