# Generated by Django 6.0.7 on 2026-07-14 14:07

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_rename_club_id_openinghours_club_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='closing_hour',
            field=models.CharField(validators=[common.validators.ValidHoursValidator()]),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='opening_hour',
            field=models.CharField(validators=[common.validators.ValidHoursValidator()]),
        ),
    ]
