# Generated by Django 6.0.7 on 2026-07-15 08:21

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0010_alter_openinghours_closing_hour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openinghours",
            name="closing_hour",
            field=models.CharField(
                validators=[common.validators.ValidHoursValidator("Incorrect time")]
            ),
        ),
        migrations.AlterField(
            model_name="openinghours",
            name="opening_hour",
            field=models.CharField(
                validators=[common.validators.ValidHoursValidator("Incorrect time")]
            ),
        ),
    ]
