name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/matchpoint/requirements.txt
    - name: Check format
      run: |
        ruff check .
    - name: Run Tests
      run: |
        pytest --cov
